### ISSUE TITLE
Site Navigation

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/satellite-dashboard#11]
## Menu Items
- [x] Create `navigation.json` with links to the following pages:
  - [x] Visualizer (home page)
  - [x] Key Events
  - [x] Analysis
  - [x] About
  - [x] Glossary

Each entry should have the following attributes:
- [x] url
- [x] title
- [x] identifier

## Menu HTML
- [x] Unordered list
- [x] Pass "class" as a property (class will change depend on if it's used in the site header or site footer)

**Comment by urchykli** [comment]
Why did I read it as ordered list? Anyway, it's finished!
