### ISSUE TITLE
Layout: Post

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/satellite-dashboard#17]
Create a page for the individual analysis posts.

Page should include:
- [x] Category
- [x] Post Title
- [x] Excerpt
- [x] Satellite Table
- [x] Authors List
- [x] Published Date
- [x] Last Updated Date
- [x] Feature Image
- [x] Content
- [x] Further Reading
- [x] Authors Block
- [x] Tags
- [x] Related Posts
- [x] Site Footer

**Comment by jnschrag** [comment]
This probably should have been split into multiple issues, but...oh well. :D

@urchykli I'd like you to start with the page structure & the page header. For the structure, I mean the HTML required for all the different components with placeholder text indicating what goes where. (eg. `<div class="related-posts">Related Posts</div>`)

<img width="736" alt="Screen Shot 2020-06-08 at 2 22 23 PM" src="https://user-images.githubusercontent.com/1896496/84066205-9008bd80-a993-11ea-858e-336bf4c42e49.png">

**Comment by urchykli** [comment]
Questions
- Will updated dates and content be part of the post content or will it be a separate piece of data?
- What's the path to access author bios using the author id?
- What's the path to access related post content using the related post id?

Data Needed
- Satellite
     -user (gov't, commercial, etc)
     -URL
     -Object name
- Updated content (depending on the answer to the question above)
- Tags
     -Name
     -URL
- Further reading
     -Title
     -Source
     -URL
-Related posts (2 per post)
     -Featured image
     -Title
     -Author
     -Date
     -URL

**Comment by jnschrag** [comment]
@shortjared For things like the featured images, do we have the URLs for what those images will be yet?
