### ISSUE TITLE
List for Sam

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/satellite-dashboard#185]
Cesium related bug fixes we'd like to look at. @samadd, let us know what you think in terms of # of hours, and if you have any questions for us. There's only a couple of things on the list and I know you've started on one of them already. If there's any time remaining on your contract, then I think we'll hold that for helping to fix any bugs that pop up as we start doing bug testing in the next week or so. Thank you!

- [x] "View Button": when clicking on the view button, track the associated satellites and rotate the Cesium camera so they're in view (#42)
- [x] Preserving the tracked/selected state of a satellite when changing the date (from #164). If you select a satellite, and then change the date, the satellite loses focus (the orbit path & label disappears, and the camera zooms back out).

**Comment by samadd** [comment]
Thanks, Jacque - I can get on with these and that should leave some spare time at the end for such bug-fixes that may crop up.

**Comment by HP4k1h5** [comment]
Closed by #191
