### ISSUE TITLE
Clicking on the tab of a panel that is already open should close the whole side panel

### ISSUE THREAD

**Issue by HP4k1h5** [CSIS-iLab/satellite-dashboard#205]

**Comment by HP4k1h5** [comment]
Not sure if this is feasible. The panel and tabs are part of a [component](https://a11y-kit.com/packages/vue-tabs.html) that might not allow us to listen to this event.

**Comment by jnschrag** [comment]
I can confirm, this isn't possible with the Tab component that we're using.
