### ISSUE TITLE
When the user only has one filter and then removes it, the screen should return to the base state that has the "Add a filter" field.

### ISSUE THREAD

**Issue by HP4k1h5** [CSIS-iLab/satellite-dashboard#217]

**Comment by jnschrag** [comment]
@tuckabelle Can you clarify what you're seeing happen here? This is what I see, which I think is meant to be the intended behavior according to your note so I'm not entirely sure what to change.


https://user-images.githubusercontent.com/1896496/128929737-a7d531e9-6e5b-40df-ab2e-3daa5c968dc7.mp4

**Comment by tuckabelle** [comment]
Oh! This is right. When I was taking those notes, something was off and it wasn't doing that. Probably just a bug I can't manage to replicate? Or maybe I was seeing things. Dunno, but this looks good to me!
