### ISSUE TITLE
Date range: put the "X" to clear the date as a button to the right inside the input

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/satellite-dashboard#238]

**Comment by jnschrag** [comment]
@tuckabelle & @HP4k1h5  Unfortunately the plugin we use for the date picker combines the calendar & close icons as a part of the same container. I can't separate the two. If we want the clear button to be on the right, that means the calendar icon also has to be on the right.

Let me know if you'd like me to make the switch.

**Comment by tuckabelle** [comment]
oh, bummer. But yeah, can we put them the right then? Merci!
