### ISSUE TITLE
Component: Post Block

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/satellite-dashboard#26]
For each post, include:

- [ ] Category (optional)
- [ ] Title/link to article
- [ ] Published Date
- [ ] Written By
- [ ] Excerpt
- [ ] Feature Image (optional)

For "optional" fields, make their rendering conditional based on a prop so they can be excluded based on the context of where the post block component is being used.

## Notes
-  The styling of the post block component changes based on where it is used (analysis archive or the visualizer).

**Comment by urchykli** [comment]
@jnschrag Are tagIDs equivalent to categories?  If not, we need categories.  If so...I have other questions 😂

**Comment by jnschrag** [comment]
Good catch, @urchykli. No tagIDs are for tags and only appear on single post pages. Looking at the schema, it looks like the categories are eventTypeIDs. For now, go ahead and render that. I'll talk to @shortjared about how to get the actual nice event type name to show up. :)
