### ISSUE TITLE
Component: Event Block

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/satellite-dashboard#42]
This component is used throughout the visualizer when showing information about an event.

- [x] Title: by default, this should be the distance of the event but should be overridable via a prop
- [x] Distance: only show if title is not the distance
- [x] Date
- [x] View button: Jumps visualization to date & time of close approach with satellites in focus
  - [x] Use first satellite's position to control visualizer's position
- [x] Compare Objects button: Opens the Magic Chart component (#50)

## Satellites
This component should take an array of satellites. For each satellite involved, display this information:
- [x] Status
- [x] Name
- [x] ID
- [x] 3 letter country code
- [x] Pin button (toggles whether that satellite is pinned or not)

**Note:** When used on the Object Details component, do not show the satellite that has the same ID as the selected object.

**Comment by jnschrag** [comment]
This component was started by #118.

**Comment by jnschrag** [comment]
@samadd - hoping I can get your insights on the remaining task for this component.

If you click on the "View Orbit" button in the close approach list (visible if you click the "view latest" tab and a few other places), the visual updates and only the two relevant satellites are visible. That's 100% what we want. The issue is that depending on where those satellites are located, you might not realize they're there as they can be hidden on the other side of the earth.

What I was wondering is if it would be possible to set those satellites to being tracked/selected when that icon is clicked. That button works as a `<nuxt-link>` so it updates the URL with the selected satellites in question. I had attempted to make some changes to the `handleQueryString()` function in [FocusList.vue](https://github.com/CSIS-iLab/satellite-dashboard/blob/main/components/visualizer/FocusList.vue#L163) by having it run after the cesium component is run. The issue is that the API call that actually gets the orbital data happens after this function does, so there are no Cesium entities to set to tracked or selected.

I think the two use cases where we'd want the satellites to be focused (meaning the camera has zoomed in on their general direction,  like on the 1st satellite in the pair), their orbital paths are visible, and their name labels are visible are:
1. If the user navigates to the site with satellites selected, eg: https://satellitedashboard.org/?satids=32768,42740&date=2021-07-15&time=0
2. While using the site, if the user navigates to a new URL like the above (when the query parameters update)

Any ideas on if this is possible, Sam? If not, then an acceptable alternative might be to move the Cesium camera so the satellites are in view, but I'm still not sure _when_ in the lifecycle you'd be able to do that.

**Comment by samadd** [comment]
I think this should be possible. As you've stated, you can't do it directly through watching the query string as Cesium can't do anything until the orbital paths are loaded, which only happens after the query string change detection.

I think we could watch the satIds query string parameter in the CesiumViewer component, however, but rather than do anything to non-existent entities, we could make a memo to do something (ie show orbits and track) whenever the data does arrive (or not if the query string has changed to nothing). So the Cesium viewer would have some internal property that if set, the specified satellites have their orbits shown and are tracked (or the first one is, or something like that).

I'm trying something like that on a branch just now.

**Comment by jnschrag** [comment]
> I'm trying something like that on a branch just now.

That makes sense to me. Doesn't Cesium already kind of do this in a roundabout way by watching the `visibleSatellites`? But I guess you're right, Cesium doesn't know or care where those visible satellites are coming from, so we would  need to explicitly have it watch the query param for sat IDs too.

Do you have an estimate on how long something like that would take? I want to be mindful of the number of hours we've got left on our contract with you before committing to moving ahead with this.

**Comment by samadd** [comment]
It was almost there when I spent an hour on it the other night, so I'm
thinking another 1/2 hour to get it working, tops?

On that note, it might be useful to compile a list of items for me to be
looking at, as there have been a few things mentioned in a few different
threads. There was persisting orbital paths / selections between date
changes, for example.

-Sam

**Comment by jnschrag** [comment]
Sounds good! Then let's go ahead and have you finish that up then. :)

And yes, absolutely. Let me go back through the threads and put together a list and we can figure out what is doable and what isn't in the time remaining.
